services:
  app:
    image: '63dd0dfb1833'
    container_name: app
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      - DB_URL=jdbc:postgresql://db:5432/postgres
      - DB_USER=postgres
      - DB_PASSWORD=passpass
    depends_on:
      - db
  db:
    image: 'postgres'
    container_name: db
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passpass
    volumes:
      - ./src/main/resources/db/migration/init.sql:/docker-entrypoint-initdb.d/init.sql