server:
  port: 8080
spring:
  application:
    name: v5
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
token:
  lifetime: 10
  key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#      springframework:
#        messaging:
#          simp: TRACE
#        web: DEBUG
#        socket: TRACE
#        security:
#          web: DEBUG